name: Docker Build Check

on:
  push:
    branches:
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          curl -L "https://github.com/docker/compose/releases/download/v2.20.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose

      - name: Generate .env file
        run: |
          echo ${{ secrets.BACK_ENV }} > server/.env

      - name: Build Docker Compose
        run: docker-compose -f docker-compose.yml build

      - name: Generate Tar
        run: |
          docker save area-server -o server.tar
          docker save area-back -o back.tar
          sudo chmod 644 server.tar back.tar
        #docker save area-front -o front.tar
      - name: Upload binary to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          source: "*.tar"
          target: "/home/${{ secrets.VPS_USER }}/area"
          debug: true

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Restart service on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/${{ secrets.VPS_USER }}/area
            docker load -i server.tar
            docker load -i back.tar
            docker-compose -f docker-compose.yml down
            docker-compose -f docker-compose.yml up -d
          #docker load -i front.tar
